'use strict';
const $ = (id) => document.getElementById(id);
let records = []; let editingId = ''; let usernamesVisible = false;
const pmT = (key, vars) => window.i18n?.tSync?.(key, vars) || key;
function show(id) { for (const name of ['unsupported','consent','setup','unlock','manager']) $(name).classList.toggle('hidden', name !== id); $('lockBtn').classList.toggle('hidden', id !== 'manager'); }
function message(text, error = false) { $('status').textContent = text; $('status').style.color = error ? '#fca5a5' : '#7dd3fc'; }
function errorText(error) { const raw=String(error?.message||error||''); if(raw.includes('weak-master-password'))return pmT('passwordManager.errors.weakMasterPassword'); const code=raw.split(':').pop().trim(); const keys={'vault-locked':'vaultLocked','invalid-master-password':'invalidMasterPassword','unlock-rate-limited':'unlockRateLimited','verification-busy':'verificationBusy','secure-storage-unavailable':'secureStorageUnavailable','record-not-found':'recordNotFound','authorization-required':'authorizationRequired','activation-consent-required':'activationConsentRequired'}; return pmT(`passwordManager.errors.${keys[code]||'generic'}`); }
function masterPasswordRules(value) { return { length:value.length>=12&&value.length<=256, lower:/[a-z]/.test(value), upper:/[A-Z]/.test(value), number:/[0-9]/.test(value), symbol:/[^A-Za-z0-9\s]/.test(value) }; }
function validateSetupPassword() { const password=$('setupPassword').value; const confirmValue=$('setupConfirm').value; const rules=masterPasswordRules(password); for(const [name,valid] of Object.entries(rules)){const item=document.querySelector(`[data-rule="${name}"]`);item?.classList.toggle('valid',valid);item?.classList.toggle('invalid',!valid);} const matches=password.length>0&&password===confirmValue; $('matchRule').textContent=pmT(matches?'passwordManager.validation.passwordsMatch':'passwordManager.validation.passwordsMismatch'); $('matchRule').classList.toggle('valid',matches); $('matchRule').classList.toggle('invalid',!matches); const ready=Object.values(rules).every(Boolean)&&matches; $('createBtn').disabled=!ready; return ready; }
async function refresh() { const status = await vaultAPI.status(); if($('lockTimeout')) $('lockTimeout').value=String(status.lockTimeoutMs||300000); if (!status.supported) return show('unsupported'); if (!status.enabled) return show('consent'); if (!status.exists) return show('setup'); if (status.locked) return show('unlock'); show('manager'); records = await vaultAPI.list(); render(); }
function maskedUsername(value) { return '•'.repeat(Math.min(24, Math.max(8, Array.from(String(value || '')).length))); }
function updateUsernameVisibilityButton(){const button=$('toggleUsernamesBtn');const key=usernamesVisible?'passwordManager.usernames.hide':'passwordManager.usernames.show';const label=pmT(key);button.setAttribute('aria-pressed',String(usernamesVisible));button.setAttribute('aria-label',label);button.title=label;}
function render() { const query = $('search').value.toLowerCase(); const root = $('records'); root.replaceChildren(); for (const item of records.filter((r) => `${r.origin} ${r.username}`.toLowerCase().includes(query))) { const row=document.createElement('div'); row.className='record'; const info=document.createElement('div'); info.className='record-info'; const site=document.createElement('strong'); site.textContent=item.origin; const user=document.createElement('span'); user.textContent=usernamesVisible?item.username:maskedUsername(item.username); user.setAttribute('aria-label',usernamesVisible?pmT('passwordManager.usernames.label',{username:item.username}):pmT('passwordManager.usernames.hidden')); info.append(site,user); const actions=document.createElement('div'); actions.className='record-actions'; const edit=document.createElement('button'); edit.textContent=pmT('passwordManager.actions.edit'); edit.className='ghost'; edit.onclick=()=>editRecord(item); const del=document.createElement('button'); del.textContent=pmT('passwordManager.actions.delete'); del.className='danger-btn'; del.onclick=()=>deleteRecord(item); actions.append(edit,del); row.append(info,actions); root.append(row); } if(!root.children.length){const empty=document.createElement('p');empty.textContent=pmT('passwordManager.records.empty');root.append(empty);} }
async function auth(promptText=pmT('passwordManager.prompts.enterMaster')) { const master=window.prompt(promptText); if(!master) throw new Error('cancelled'); return vaultAPI.authorize(master); }
async function editRecord(item) { try { const token=await auth(pmT('passwordManager.prompts.edit')); const secret=await vaultAPI.reveal(item.id,token); editingId=item.id; $('editorTitle').textContent=pmT('passwordManager.editor.editTitle'); $('origin').value=item.origin; $('origin').disabled=true; $('username').value=secret.username; $('password').value=secret.password; $('editor').showModal(); setTimeout(()=>{$('password').value='';},15000); } catch(e){if(String(e.message)!=='cancelled')message(errorText(e),true);} }
async function deleteRecord(item) { if(!confirm(pmT('passwordManager.confirm.delete',{origin:item.origin})))return; try{const token=await auth(pmT('passwordManager.prompts.delete'));await vaultAPI.remove(item.id,token);message(pmT('passwordManager.messages.deleted'));await refresh();}catch(e){if(String(e.message)!=='cancelled')message(errorText(e),true);} }
$('setupPassword').addEventListener('input',validateSetupPassword); $('setupConfirm').addEventListener('input',validateSetupPassword);
$('createBtn').onclick=async()=>{if(!validateSetupPassword())return message(pmT('passwordManager.validation.requirementsNotMet'),true);const password=$('setupPassword').value;$('setupPassword').value=$('setupConfirm').value='';try{await vaultAPI.create(password);message(pmT('passwordManager.messages.created'));await refresh();}catch(e){message(errorText(e),true);}};
function updateActivationButton(){ $('enableBtn').disabled=!($('noticeCheck').checked&&$('activationCheck').checked); }
$('noticeCheck').onchange=updateActivationButton;
$('activationCheck').onchange=updateActivationButton;
$('enableBtn').onclick=async()=>{if($('enableBtn').disabled)return;try{const status=await vaultAPI.status();await vaultAPI.setEnabled(true,{noticeVersion:status.noticeVersion,activationVersion:status.activationVersion,noticeAcknowledged:true,activationConfirmed:true});$('noticeCheck').checked=$('activationCheck').checked=false;updateActivationButton();message(pmT('passwordManager.messages.enabled'));await refresh();}catch(e){message(errorText(e),true);}};
$('laterBtn').onclick=()=>window.close();
$('unlockBtn').onclick=async()=>{const password=$('unlockPassword').value;$('unlockPassword').value='';try{await vaultAPI.unlock(password);message(pmT('passwordManager.messages.unlocked'));await refresh();}catch(e){message(errorText(e),true);}};
$('unlockPassword').addEventListener('keydown',(event)=>{if(event.key!=='Enter'||event.isComposing)return;event.preventDefault();$('unlockBtn').click();});
$('lockBtn').onclick=async()=>{usernamesVisible=false;updateUsernameVisibilityButton();await vaultAPI.lock();await refresh();}; $('search').oninput=render;
$('lockTimeout').onchange=async()=>{try{await vaultAPI.setLockTimeout(Number($('lockTimeout').value));message(pmT('passwordManager.messages.autoLockUpdated'));}catch(e){message(errorText(e),true);await refresh();}};
$('toggleUsernamesBtn').onclick=()=>{usernamesVisible=!usernamesVisible;updateUsernameVisibilityButton();render();};
$('addBtn').onclick=()=>{editingId='';$('editorTitle').textContent=pmT('passwordManager.editor.addTitle');$('origin').disabled=false;$('origin').value=$('username').value=$('password').value='';$('editor').showModal();};
$('saveBtn').onclick=async(e)=>{e.preventDefault();try{if(editingId){const token=await auth(pmT('passwordManager.prompts.saveChanges'));await vaultAPI.update(editingId,{username:$('username').value,password:$('password').value},token);}else await vaultAPI.save({origin:$('origin').value,username:$('username').value,password:$('password').value});$('password').value='';$('editor').close();message(pmT('passwordManager.messages.saved'));await refresh();}catch(err){message(errorText(err),true);}};
$('changeMasterBtn').onclick=async()=>{const oldPass=prompt(pmT('passwordManager.prompts.currentMaster'));if(!oldPass)return;const next=prompt(pmT('passwordManager.prompts.newMaster'));if(!next)return;try{const token=await vaultAPI.authorize(oldPass);await vaultAPI.changeMaster(oldPass,next,token);message(pmT('passwordManager.messages.masterChanged'));}catch(e){message(errorText(e),true);}};
$('resetBtn').onclick=async()=>{if(!confirm(pmT('passwordManager.confirm.reset')))return;try{const token=await auth(pmT('passwordManager.prompts.reset'));await vaultAPI.reset(token);message(pmT('passwordManager.messages.reset'));await refresh();}catch(e){if(String(e.message)!=='cancelled')message(errorText(e),true);}};
$('disableBtn').onclick=async()=>{if(!confirm(pmT('passwordManager.confirm.disable')))return;try{await vaultAPI.setEnabled(false);message(pmT('passwordManager.messages.disabled'));await refresh();}catch(e){message(errorText(e),true);}};
function refreshLocalizedDynamicText() { updateUsernameVisibilityButton(); validateSetupPassword(); if (!$('manager').classList.contains('hidden')) render(); }
window.addEventListener('ardali:languageChanged', refreshLocalizedDynamicText);
async function initialize() {
    await window.i18n.init();
    window.ardali?.onSettingsReload?.(async (settings) => {
        const lang=String(settings?.ui?.language||settings?.lang||'').trim();
        if(lang&&lang!==window.i18n.getLanguage()) await window.i18n.setLanguage(lang,{skipPersist:true});
    });
    await refresh();
}
initialize().catch((e)=>message(errorText(e),true));
