// This file is autogenerated. Changes will be overwritten.
#include "GUWOQ4XZIE/moc_bookmark_candidate_provider.cpp"
#include "GUWOQ4XZIE/moc_composite_navigation_candidate_provider.cpp"
#include "GUWOQ4XZIE/moc_frequent_sites_candidate_provider.cpp"
#include "GUWOQ4XZIE/moc_history_candidate_provider.cpp"
