// This file is autogenerated. Changes will be overwritten.
#include "DASOPFMBVJ/moc_audio_capture_service.cpp"
#include "DASOPFMBVJ/moc_audio_device_manager.cpp"
#include "Z4VFSVRC3A/moc_song_finder_settings.cpp"
#include "Z4VFSVRC3A/moc_song_recognition_service.cpp"
