// This file is autogenerated. Changes will be overwritten.
#include "BZSKHNWXV4/moc_system_memory_pressure_monitor.cpp"
#include "BZSKHNWXV4/moc_tab_manager.cpp"
#include "BZSKHNWXV4/moc_tab_performance_manager.cpp"
