// This file is autogenerated. Changes will be overwritten.
#include "BZSKHNWXV4/moc_detached_tab_window_controller.cpp"
#include "BZSKHNWXV4/moc_tab_drag_controller.cpp"
#include "BZSKHNWXV4/moc_tab_group_model.cpp"
#include "BZSKHNWXV4/moc_tab_strip_animator.cpp"
#include "BZSKHNWXV4/moc_tab_strip_widget.cpp"
#include "BZSKHNWXV4/moc_tab_window_registry.cpp"
