# CMake generated Testfile for 
# Source directory: /home/muhammetdli/ArDali
# Build directory: /home/muhammetdli/ArDali/build-step2-debug-20260917
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("browser-policy-test" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-policy-test")
set_tests_properties("browser-policy-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;487;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-security-utils" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-security-utils-test")
set_tests_properties("browser-security-utils" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;494;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-web-engine-hardware-acceleration" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-web-engine-hardware-acceleration-test")
set_tests_properties("browser-web-engine-hardware-acceleration" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;501;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-web-engine-memory-policy" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-web-engine-memory-policy-test")
set_tests_properties("browser-web-engine-memory-policy" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;508;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-eq-preset-repository" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-eq-preset-repository-test")
set_tests_properties("browser-eq-preset-repository" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;516;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-web-audio-effects" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-web-audio-effects-test")
set_tests_properties("browser-web-audio-effects" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_DISABLE_SANDBOX=1;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;538;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-installed-package-layout" "/usr/bin/cmake" "-DARDALI_BUILD_DIR=/home/muhammetdli/ArDali/build-step2-debug-20260917" "-DARDALI_INSTALL_BINDIR=bin" "-P" "/home/muhammetdli/ArDali/browser/cmake/verify_install_layout.cmake")
set_tests_properties("browser-installed-package-layout" PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;544;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-credential-vault-test" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-credential-vault-test")
set_tests_properties("browser-credential-vault-test" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;558;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-password-autofill-test" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-password-autofill-test")
set_tests_properties("browser-password-autofill-test" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_DISABLE_SANDBOX=1;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;577;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-password-manager-page-test" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-password-manager-page-test")
set_tests_properties("browser-password-manager-page-test" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;588;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-song-finder" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-song-finder-test")
set_tests_properties("browser-song-finder" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;601;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-media-download-service" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-media-download-service-test")
set_tests_properties("browser-media-download-service" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;610;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-general-download-manager" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-general-download-manager-test")
set_tests_properties("browser-general-download-manager" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;618;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-new-tab-asset-resolver" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-new-tab-asset-resolver-test")
set_tests_properties("browser-new-tab-asset-resolver" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;625;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-download-ui-model" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-download-ui-model-test")
set_tests_properties("browser-download-ui-model" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;631;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-local-media-routing" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-local-media-routing-test")
set_tests_properties("browser-local-media-routing" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;637;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-application-identity" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-application-identity-test")
set_tests_properties("browser-application-identity" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;645;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-media-platform-registry" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-media-platform-registry-test")
set_tests_properties("browser-media-platform-registry" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;653;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-desktop-tab-system" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-desktop-tab-system-test")
set_tests_properties("browser-desktop-tab-system" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=xcb" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;669;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-tab-drag-controller" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-tab-drag-controller-test")
set_tests_properties("browser-tab-drag-controller" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=xcb" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;686;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-critical-tab-drag-scenario" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-critical-tab-drag-scenario-test")
set_tests_properties("browser-critical-tab-drag-scenario" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;703;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-runtime-feature-integration" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-runtime-feature-integration-test")
set_tests_properties("browser-runtime-feature-integration" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;737;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-phase2a-policy" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-phase2a-policy-test")
set_tests_properties("browser-phase2a-policy" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;747;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-tab-scheduler-retry" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-tab-scheduler-retry-test")
set_tests_properties("browser-tab-scheduler-retry" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;756;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-tab-hover-card" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-tab-hover-card-test")
set_tests_properties("browser-tab-hover-card" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;767;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-address-input-resolver" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-address-input-resolver-test")
set_tests_properties("browser-address-input-resolver" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;776;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-omnibox-navigation-integration" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-omnibox-navigation-integration-test")
set_tests_properties("browser-omnibox-navigation-integration" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;785;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-smart-omnibox-phase2" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-smart-omnibox-phase2-test")
set_tests_properties("browser-smart-omnibox-phase2" PROPERTIES  _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;798;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("smart_omnibox_phase2_1_test" "/home/muhammetdli/ArDali/build-step2-debug-20260917/smart_omnibox_phase2_1_test")
set_tests_properties("smart_omnibox_phase2_1_test" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" TIMEOUT "90" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;835;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("ardali-phase22d" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-phase22d-test")
set_tests_properties("ardali-phase22d" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" TIMEOUT "90" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;859;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("ardali-phase22d-integration" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-phase22d-integration-test")
set_tests_properties("ardali-phase22d-integration" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;883;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-site-permission" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-site-permission-test")
set_tests_properties("browser-site-permission" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" TIMEOUT "90" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;900;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("browser-context-menu" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-browser-context-menu-test")
set_tests_properties("browser-context-menu" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu" TIMEOUT "90" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;912;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
add_test("language-manager-test" "/home/muhammetdli/ArDali/build-step2-debug-20260917/ardali-language-manager-test")
set_tests_properties("language-manager-test" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" TIMEOUT "30" _BACKTRACE_TRIPLES "/home/muhammetdli/ArDali/CMakeLists.txt;936;add_test;/home/muhammetdli/ArDali/CMakeLists.txt;0;")
